[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
ruby_build_opts = "CC=gcc-14 CXX=g++-14"

# Global mise configuration for system-wide tasks

[tasks.release-daily]
description = "Tag a release: vYYYY.mm.dd.patch (auto-increments patch for same day)"
alias = "rd"
run = '''
#!/usr/bin/env bash
set -euo pipefail

# Ensure we're in a git repository
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "Error: Not inside a git repository"
    exit 1
fi

# Today’s date parts
YEAR=$(date +%Y)
MONTH=$(date +%m)
DAY=$(date +%d)
PREFIX="v${YEAR}.${MONTH}.${DAY}"

# Highest existing patch for today, default to -1
LAST_PATCH=$(git tag -l "${PREFIX}.*" | sed 's/.*\.\([0-9]\+\)$/\1/' | sort -n | tail -n1)
LAST_PATCH=${LAST_PATCH:--1}

PATCH=$((LAST_PATCH + 1))
TAG="${PREFIX}.${PATCH}"

echo "Pushing latest commits before tagging..."
git push origin

echo "Creating release tag: $TAG"
git tag -a "$TAG" -m "Release $TAG"
git push origin "$TAG"
echo "Tagged and pushed $TAG"
'''

# Optional: Add related global tasks for release management
[tasks.release-list]
description = "List today's release tags"
alias = "rls"
run = '''
#!/usr/bin/env bash
YEAR=$(date +%Y)
MONTH=$(date +%m)
DAY=$(date +%d)
PREFIX="v${YEAR}.${MONTH}.${DAY}"
echo "Today's release tags (${PREFIX}.*):"
git tag -l "${PREFIX}.*" | sort -V
'''
