git:
  paging:
    colorArg: always
    pager: delta --line-numbers --dark --paging=never

services:
  "gitlab.zero-one-group.com": "gitlab:gitlab.zero-one-group.com"

os:
  editPreset: "nvim"
  open: "xdg-open {{filename}} >/dev/null"

gui:
  authorColors:
    "Muhamad Iqbal": "#4682B4"
  theme:
    selectedLineBgColor:
      - reverse

customCommands:
  - key: "<c-r>"
    context: "commits"
    command: 'hub browse -- "commit/{{.SelectedLocalCommit.Hash}}"'
  - key: "a"
    context: "files"
    command: "git {{if .SelectedFile.HasUnstagedChanges}} add {{else}} reset {{end}} {{.SelectedFile.Name | quote}}"
    description: "Toggle file staged"
  - key: "<C-f>"
    context: "global"
    command: "git fetch --all"
    loadingText: "Fetching all changes"
    subprocess: true
  - key: "n"
    context: "localBranches"
    prompts:
      - type: "menu"
        title: "What kind of branch is it?"
        key: "BranchType"
        options:
          - name: "feature"
            description: "a feature branch"
            value: "feature"
          - name: "fix"
            description: "a fix branch"
            value: "fix"
          - name: "hotfix"
            description: "a hotfix branch"
            value: "hotfix"
          - name: "dev"
            description: "a playground branch"
            value: "dev"
      - type: "input"
        title: "What is the new branch name?"
        key: "BranchName"
        initialValue: ""
    command: >
      bash -c 'branch_type="{{.Form.BranchType}}"; branch_name="{{.Form.BranchName}}"; sanitized_branch_name=$(echo "$branch_name" | sed "s/ /-/g"); new_branch="${branch_type}/${sanitized_branch_name}"; git checkout -b "$new_branch"'
    loadingText: "Creating branch"
